FROM php:8.3-fpm

# 시스템 패키지 & PHP 확장
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
      libicu-dev libzip-dev zip git unzip libonig-dev; \
    docker-php-ext-install -j$(nproc) intl pdo_mysql opcache; \
    pecl install redis; docker-php-ext-enable redis; \
    apt-get clean; rm -rf /var/lib/apt/lists/*

# PHP 설정
COPY php.ini /usr/local/etc/php/php.ini

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html